Vagrant.configure(2) do |config|
  
  config.vm.box = "ubuntu/xenial64"

  config.vm.provision "shell", path: "../public_scripts/xenial-workarounds.sh"

  config.vm.provision "ansible" do |ansible|
  	# ansible.playbook = "xenial-python.yml"
    ansible.playbook = "../ansiblePlaybooks/site.yml"
  end

end
