- hosts: all
  gather_facts: False

  tasks:
    - name: install python2
      raw: sudo bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qy python-minimal)"
    - name: install aptitude
      raw: sudo bash -c "test -e /usr/bin/aptitude || (apt -qqy update && apt install -qy aptitude)"

- name: apply common configuration to all nodes
  hosts: all

  roles:
    - common
    - postfix

- name: install git on git client nodes
  hosts: tag_Git_Yes

  roles:
    - git-client
    
- name: install java on java client nodes
  hosts: tag_Java_Yes

  roles:
    - java

- name: install node on node client nodes
  hosts: tag_Node_Yes

  roles:
    - node
