# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.ssh.insert_key = true

  config.vm.box_check_update = true

  config.vm.network "private_network", ip: "192.168.207.23"

  config.vm.hostname = "ansibleVagrant"

  config.vm.provider "virtualbox" do |v|
    v.memory = "1024"
    v.name = "ansibleVagrant"
  end

  #
  # Run Ansible from the Vagrant Host
  #
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../ansiblePlaybooks/site.yml"
  end

  config.vm.provision "shell", path: "../public_scripts/backups.sh"
  config.vm.provision "shell", path: "../public_scripts/git.sh"

  config.vm.provision "shell", inline: <<-SHELL
    ls -lathr /bak/
    reboot
  SHELL
  
end
