---
- name: update and upgrade all packages
  apt: 
    upgrade: safe 
    update_cache: yes
  become: true
- name: ensure aptitude is at the latest version
  apt: 
    pkg: aptitude 
    state: latest
  become: true
- name: ensure ntp is at the latest version
  apt: 
    pkg: ntp 
    state: latest
  become: true
  notify:
      - restart ntp
- name: set timezone
  copy:
    content: 'America/Detroit'
    dest: /etc/timezone
    owner: root
    group: root
    mode: 0644
    backup: yes
  become: true
  notify:
    - update timezone
- name: Set EDITOR
  lineinfile: 
    dest: /etc/environment 
    state: present 
    regexp: '^EDITOR=' 
    line: 'EDITOR=/usr/bin/vi'
  become: true 